name: Test Workflow  # Ime delovnega toka

on:
  push:
    branches:
      - master # Test se zažene po potisku na glavno vejo

jobs:
  setup_environment:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ['3.8', '3.9'] # Uporaba matrice samo za prvo nastavitev okolja
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Uporabi akcijo za preverjanje kode

      - name: Set up Python
        uses: actions/setup-python@v2  # Uporabi akcijo za nastavitev Pythona
        with:
          python-version: ${{ matrix.python-version }} # Dinamična izbira verzije Pythona iz matrice

      - name: Install dependencies  # Namesti odvisnosti s pip
        run: |
          chmod +x ./venv.sh
          ./venv.sh

      - name: Save environment setup status  # Shrani rezultat namestitve v datoteko setup_status.txt
        run: |
          echo "Okolje uspešno nameščeno!" > setup_status.txt

      - name: Upload setup status
        uses: actions/upload-artifact@v2
        with:
          name: setup-status
          path: setup_status.txt

  run_tests:
    runs-on: self-hosted
    needs: setup_environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Uporabi akcijo za preverjanje kode

      - name: Download setup status
        uses: actions/download-artifact@v2
        with:
          name: setup-status

      - name: Check environment setup status
        run: |
          if [ -f setup_status.txt ]; then
            cat setup_status.txt
          else
            echo "Napaka: Namestitev okolja ni uspela. Preverite dnevnike namestitve."
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Run tests
        run: |
          source $(pwd)/.venv/bin/activate
          pytest test.py
