name: Test Workflow  # Ime delovnega toka

on:
  push:
    branches:
      - master # Test se zažene po potisku na glavno vejo

jobs:
  setup_environment:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9] # Matrix različic Pythona
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Uporabi akcijo za preverjanje kode

      - name: Set up Python
        uses: actions/setup-python@v2  # Uporabi akcijo za nastavitev Pythona
        with:
          python-version: ${{ matrix.python-version }}  # Dinamično določi različico Pythona iz matrice

      - name: Install dependencies  # Namesti odvisnosti s pip
        run: |
          chmod +x ./venv.sh
          ./venv.sh
          
      - name: Save environment setup artifacts  # Shrani rezultat namestitve v datoteko setup_status.txt
        run: |
          echo "Okolje uspešno nameščeno!" > setup_status.txt

      - name: Upload setup artifacts  # Naloži rezultate namestitve kot artefakte
        uses: actions/upload-artifact@v2
        with:
          name: setup-artifacts  # Ime artefakta
          path: setup_status.txt

  run_tests:
    runs-on: self-hosted
    needs: setup_environment
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9] # Matrix različic Pythona
    steps:
      - name: Download setup artifacts  # Prenesi artefakte iz prejšnjega dela
        uses: actions/download-artifact@v2
        with:
          name: setup-artifacts

      - name: Check environment setup status  # Preveri status namestitve okolja
        run: |
          if [ -f setup_status.txt ]; then
            cat setup_status.txt  # Izpiši vsebino datoteke
          else
            echo "Napaka: Namestitev okolja ni uspela. Preverite dnevnike namestitve."
            exit 1

      - name: Set up Python
        uses: actions/setup-python@v2  # Uporabi akcijo za nastavitev Pythona
        with:
          python-version: ${{ matrix.python-version }}  # Dinamično določi različico Pythona iz matrice

      - name: Install dependencies and run tests  # Namesti odvisnosti in zaženi teste
        run: |
          chmod +x ./venv.sh
          ./venv.sh
          pytest test.py
