name: Test Workflow

on:
  push:
    branches:
      - master

jobs:
  setup_environment:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies and create virtual environment
        run: |
          chmod +x ./venv.sh
          ./venv.sh

      - name: Save environment setup artifacts
        run: |
          echo "Okolje uspešno nameščeno!" > setup_status.txt
        continue-on-error: true

      - name: Upload setup artifacts
        uses: actions/upload-artifact@v2
        with:
          name: setup-artifacts
          path: |
            setup_status.txt
            .venv   

  run_tests:
    runs-on: self-hosted
    needs: setup_environment
    steps:
      - name: Download setup artifacts
        uses: actions/download-artifact@v2
        with:
          name: setup-artifacts

      - name: Check environment setup status
        run: |
          if [ -f setup_status.txt ]; then
            cat setup_status.txt
          else
            echo "Napaka: Namestitev okolja ni uspela. Preverite dnevnike namestitve."
            echo "Napaka: Namestitev okolja ni uspela. Preverite dnevnike namestitve." > error.txt
          fi
        continue-on-error: true

      - name: Run tests
        run: |
          source .venv/bin/activate 
          pytest test.py
        continue-on-error: true

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            pytest_output.txt  # Add your test output file

      - name: Check for test errors
        run: |
          if [ -f error.txt ]; then
            echo "Napaka: Testi so spodleteli. Glejte dnevnike testiranja za podrobnosti."
            echo "Napaka: Testi so spodleteli. Glejte dnevnike testiranja za podrobnosti." > test_error.txt
            exit 1
          fi
